### ISSUE TITLE
Installation instructions should be extended, if sb new to go

### ISSUE THREAD

**Issue by nyuwec** [abesto/easyssh#8]
OSX:
1. `brew install go`
2. `mkdir ~/.gocode`
3. `export GOPATH=/Users/yourusername/.gocode`

**Comment by nyuwec** [comment]
I will create a PR, but because of #9 I was not able to install easyssh.

**Comment by abesto** [comment]
Added https://github.com/abesto/easyssh#if-youre-new-to-go, let me know if this is what you had in mind.
Thanks!

**Comment by nyuwec** [comment]
thanks, I created a one-liner PR to make sure where to look for the executable. :)
